"use client";
import {createContext,useContext,useEffect,useMemo,useState} from "react";
import {money} from "./products";
import {track} from "./track";
export type CartItem={slug:string;name:string;color:string;giftWrap:boolean;quantity:number;price:number};
type CartValue={items:CartItem[];open:boolean;setOpen:(v:boolean)=>void;add:(item:Omit<CartItem,"quantity">)=>void;change:(slug:string,color:string,giftWrap:boolean,delta:number)=>void;clear:()=>void;subtotal:number};
const CartContext=createContext<CartValue|null>(null);const giftPrice=80000;
export function CartProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<CartItem[]>([]);const[open,setOpen]=useState(false);const[ready,setReady]=useState(false);useEffect(()=>{try{setItems(JSON.parse(localStorage.getItem("humm-cart")||"[]").map((x:CartItem)=>({...x,giftWrap:!!x.giftWrap})))}catch{}setReady(true)},[]);useEffect(()=>{if(ready)localStorage.setItem("humm-cart",JSON.stringify(items))},[items,ready]);const add=(item:Omit<CartItem,"quantity">)=>{setItems(current=>{const found=current.find(x=>x.slug===item.slug&&x.color===item.color&&x.giftWrap===item.giftWrap);return found?current.map(x=>x===found?{...x,quantity:x.quantity+1}:x):[...current,{...item,quantity:1}]});track("add_to_cart",item.slug,{color:item.color,giftWrap:item.giftWrap});setOpen(true)};const change=(slug:string,color:string,giftWrap:boolean,delta:number)=>setItems(current=>current.map(x=>x.slug===slug&&x.color===color&&x.giftWrap===giftWrap?{...x,quantity:x.quantity+delta}:x).filter(x=>x.quantity>0));const subtotal=useMemo(()=>items.reduce((s,x)=>s+(x.price+(x.giftWrap?giftPrice:0))*x.quantity,0),[items]);return <CartContext.Provider value={{items,open,setOpen,add,change,clear:()=>setItems([]),subtotal}}>{children}<div className={`drawer-backdrop ${open?"show":""}`} onClick={()=>setOpen(false)}/><aside className={`cart-drawer ${open?"open":""}`} aria-hidden={!open}><div className="drawer-head"><div><span>your happy cart</span><h2>Giỏ hàng</h2></div><button onClick={()=>setOpen(false)} aria-label="Đóng giỏ">×</button></div><div className="drawer-items">{!items.length?<p className="empty-cart">Chưa có chiếc đèn nào ở đây.<br/>Một người bạn đang chờ bạn chọn ✦</p>:items.map(x=><div className="drawer-item" key={`${x.slug}-${x.color}-${x.giftWrap}`}><div className={`cart-thumb ${x.slug}`}>☼</div><div><b>{x.name}</b><small>{x.color}{x.giftWrap?" · Gói quà":""}</small><div className="qty"><button onClick={()=>change(x.slug,x.color,x.giftWrap,-1)}>−</button><span>{x.quantity}</span><button onClick={()=>change(x.slug,x.color,x.giftWrap,1)}>+</button></div></div><strong>{money((x.price+(x.giftWrap?giftPrice:0))*x.quantity)}</strong></div>)}</div>{items.length>0&&<div className="drawer-total"><div><span>Tạm tính</span><b>{money(subtotal)}</b></div><small>{subtotal>=1500000?"Bạn được miễn phí vận chuyển ✦":`Thêm ${money(1500000-subtotal)} để được miễn phí giao hàng`}</small><a href="/shop/checkout" onClick={()=>{track("begin_checkout",undefined,{items:items.length});setOpen(false)}}>Đi đến thanh toán →</a></div>}</aside></CartContext.Provider>}
export function useCart(){const value=useContext(CartContext);if(!value)throw new Error("CartProvider missing");return value}
