"use client";
import { useMemo, useState } from "react";
import { useCart } from "./cart";
import { money } from "./products";
import { productPrice, ShopifyProduct } from "./shopify";

export default function CatalogClient({ initialProducts, loadError = "" }: { initialProducts: ShopifyProduct[]; loadError?: string }) {
  const { items, setOpen } = useCart(); const [query, setQuery] = useState(""), [sort, setSort] = useState("newest"), [availableOnly, setAvailableOnly] = useState(false);
  const count = items.reduce((sum, item) => sum + item.quantity, 0);
  const products = useMemo(() => initialProducts.filter(p => (!availableOnly || p.availableForSale) && `${p.title} ${p.description} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase().trim())).sort((a, b) => sort === "price-low" ? productPrice(a) - productPrice(b) : sort === "price-high" ? productPrice(b) - productPrice(a) : +new Date(b.createdAt) - +new Date(a.createdAt)), [initialProducts, query, sort, availableOnly]);
  return <main className="shop-page"><nav className="nav shop-nav"><a className="logo" href="/">humm<span>.</span></a><div className="top-tabs"><a href="/">Trang chủ</a><a className="active" href="/shop" aria-current="page">Cửa hàng</a></div><button className="cart" onClick={() => setOpen(true)}>Giỏ hàng <b>{count}</b></button></nav><header className="shop-hero"><p className="eyebrow">drop 01 — soft riot</p><h1>Pick your<br /><i>happy light.</i></h1><p>Mỗi chiếc humm. được in theo từng lớp, hoàn thiện bằng tay và có một tính cách riêng.</p><span className="shop-doodle">✦</span></header><section className="shop-catalog"><div className="catalog-bar"><span>{String(products.length).padStart(2, "0")} người bạn đang chờ</span><span>Phí giao hàng được tính tại Shopify Checkout</span></div><div className="catalog-tools"><label><span>Tìm đèn</span><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Tên, màu hoặc phong cách…" /></label><label><span>Sắp xếp</span><select value={sort} onChange={e => setSort(e.target.value)}><option value="newest">Mới nhất</option><option value="price-low">Giá thấp đến cao</option><option value="price-high">Giá cao đến thấp</option></select></label><label className="stock-filter"><input type="checkbox" checked={availableOnly} onChange={e => setAvailableOnly(e.target.checked)} /> Chỉ sản phẩm còn hàng</label></div>{loadError && <p className="shopify-message">{loadError}</p>}<div className="products">{products.map((p, index) => <article className={`product tone-${index % 3}`} key={p.id}><a className={`product-art ${!p.featuredImage ? "empty-media" : ""}`} href={`/shop/${encodeURIComponent(p.handle)}`}><span className="number">{String(index + 1).padStart(2, "0")}</span><span className="new-tag">{p.availableForSale ? "made to order" : "tạm hết hàng"}</span>{p.featuredImage ? <img src={p.featuredImage.url} alt={p.featuredImage.altText || p.title} /> : <span className="media-placeholder">Ảnh đang cập nhật</span>}</a><div className="product-info"><div><h2>{p.title}</h2>{p.description && <p>{p.description}</p>}</div><a className="round-link" href={`/shop/${encodeURIComponent(p.handle)}`} aria-label={`Xem ${p.title}`}>→</a></div><strong>{money(productPrice(p))}</strong></article>)}</div>{!loadError && !products.length && <p className="shopify-message">Không tìm thấy sản phẩm phù hợp.</p>}</section><section className="shop-promise"><div><span>01</span><h3>In chậm, làm kỹ</h3><p>Mỗi chiếc đèn được in và hoàn thiện bằng tay.</p></div><div><span>02</span><h3>Dữ liệu trực tiếp</h3><p>Giá và tồn kho luôn được lấy từ Shopify.</p></div><div><span>03</span><h3>Checkout an toàn</h3><p>Thanh toán và giao hàng được xác nhận trên Shopify.</p></div></section><footer><a className="logo" href="/">humm<span>.</span></a><p>Made slowly, for joyful homes.</p><a href="/mua-hang-an-tam">Thông tin mua hàng</a></footer></main>;
}
