"use client";
import {useEffect,useState} from "react";
import {useCart} from "./cart";
import {money} from "./products";
import {getShopifyProducts,productPrice,ShopifyProduct} from "./shopify";

export default function ShopPage(){
 const{items,setOpen}=useCart();const count=items.reduce((s,x)=>s+x.quantity,0);
 const[products,setProducts]=useState<ShopifyProduct[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{getShopifyProducts().then(setProducts).catch(e=>setError(e instanceof Error?e.message:"Không tải được sản phẩm")).finally(()=>setLoading(false))},[]);
 return <main className="shop-page"><nav className="nav shop-nav"><a className="logo" href="/">humm<span>.</span></a><div className="top-tabs"><a href="/">Trang chủ</a><a className="active" href="/shop">Cửa hàng</a></div><button className="cart" onClick={()=>setOpen(true)}>Giỏ hàng <b>{count}</b></button></nav><header className="shop-hero"><p className="eyebrow">drop 01 — soft riot</p><h1>Pick your<br/><i>happy light.</i></h1><p>Mỗi chiếc humm. được in theo từng lớp, hoàn thiện bằng tay và có một tính cách riêng.</p><span className="shop-doodle">✦</span></header><section className="shop-catalog"><div className="catalog-bar"><span>{loading?"Đang tải sản phẩm":`${String(products.length).padStart(2,"0")} người bạn đang chờ`}</span><span>Miễn phí giao hàng từ 1.500.000₫</span></div>{error&&<p className="shopify-message">{error}</p>}<div className="products">{products.map((p,index)=><article className={`product tone-${index%3}`} key={p.id}><a className={`product-art ${!p.featuredImage?"empty-media":""}`} href={`/shop/${encodeURIComponent(p.handle)}`}><span className="number">{String(index+1).padStart(2,"0")}</span><span className="new-tag">{p.availableForSale?"made to order":"tạm hết hàng"}</span>{p.featuredImage&&<img src={p.featuredImage.url} alt={p.featuredImage.altText||p.title}/>}</a><div className="product-info"><div><h2>{p.title}</h2>{p.description&&<p>{p.description}</p>}</div><a className="round-link" href={`/shop/${encodeURIComponent(p.handle)}`} aria-label={`Xem ${p.title}`}>→</a></div><strong>{money(productPrice(p))}</strong></article>)}</div>{!loading&&!error&&!products.length&&<p className="shopify-message">Chưa có sản phẩm nào được xuất bản lên Humm. Headless.</p>}</section><section className="shop-promise"><div><span>01</span><h3>In chậm, làm kỹ</h3><p>Mỗi chiếc đèn được in và hoàn thiện bằng tay.</p></div><div><span>02</span><h3>Ánh sáng dịu</h3><p>Ấm áp vừa đủ cho đầu giường và góc chill.</p></div><div><span>03</span><h3>Có một không hai</h3><p>Vân in riêng biệt làm nên cá tính của từng chiếc.</p></div></section><footer><a className="logo" href="/">humm<span>.</span></a><p>Made slowly, for joyful homes.</p><a href="/">← Về trang chủ</a></footer></main>
}
