"use client";
import {use,useEffect,useState} from "react";
import {useCart} from "../cart";
import {money} from "../products";
import {getShopifyProduct,ShopifyProduct,ShopifyVariant} from "../shopify";
import {track} from "../track";

export default function ProductPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=use(params);const[product,setProduct]=useState<ShopifyProduct|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[variant,setVariant]=useState<ShopifyVariant|null>(null);const[imageIndex,setImageIndex]=useState(0);const[giftWrap,setGiftWrap]=useState(false);const{items,setOpen,add}=useCart();
 useEffect(()=>{getShopifyProduct(decodeURIComponent(slug)).then(p=>{setProduct(p);setVariant(p?.variants.nodes[0]||null);if(p)track("product_view",p.handle)}).catch(e=>setError(e instanceof Error?e.message:"Không tải được sản phẩm")).finally(()=>setLoading(false))},[slug]);
 if(loading)return <main className="not-found"><p>Đang tải sản phẩm…</p></main>;
 if(error||!product)return <main className="not-found"><h1>Không tìm thấy sản phẩm.</h1>{error&&<p>{error}</p>}<a href="/shop">← Về cửa hàng</a></main>;
 const count=items.reduce((s,x)=>s+x.quantity,0),images=product.images.nodes,currentImage=images[imageIndex],available=!!variant?.availableForSale;
 const optionNames=[...new Set(product.variants.nodes.flatMap(v=>v.selectedOptions.map(o=>o.name)))].filter(x=>x!=="Title");
 function chooseOption(name:string,value:string){const next=product!.variants.nodes.find(v=>v.selectedOptions.every(o=>o.name===name?o.value===value:variant?.selectedOptions.some(current=>current.name===o.name&&current.value===o.value)));if(next)setVariant(next)}
 return <main className="shop-page"><nav className="nav shop-nav"><a className="logo" href="/">humm<span>.</span></a><div className="top-tabs"><a href="/">Trang chủ</a><a className="active" href="/shop">Cửa hàng</a></div><button className="cart" onClick={()=>setOpen(true)}>Giỏ hàng <b>{count}</b></button></nav><section className="pdp shopify-pdp"><div className={`pdp-visual ${!currentImage?"empty-product-image":""}`}><a className="back-shop" href="/shop">← Tất cả sản phẩm</a>{currentImage&&<img className="pdp-product-image" src={currentImage.url} alt={currentImage.altText||product.title}/>} {images.length>1&&<button className="light-switch" onClick={()=>setImageIndex(i=>i===0?1:0)}><i className={imageIndex===1?"on":""}/>{imageIndex===0?"Ảnh 1":"Ảnh 2"}</button>}</div><div className="pdp-info"><p className="eyebrow">3D printed companion</p><h1>{product.title}</h1>{variant&&<strong className="pdp-price">{money(Number(variant.price.amount))}</strong>}{product.description&&<p className="pdp-story">{product.description}</p>}{optionNames.map(name=><fieldset key={name}><legend>{name} · <b>{variant?.selectedOptions.find(o=>o.name===name)?.value}</b></legend><div className="variant-options">{[...new Set(product.variants.nodes.flatMap(v=>v.selectedOptions.filter(o=>o.name===name).map(o=>o.value)))].map(value=><button className={variant?.selectedOptions.some(o=>o.name===name&&o.value===value)?"selected":""} onClick={()=>chooseOption(name,value)} key={value}>{value}</button>)}</div></fieldset>)}<label className="gift-option"><input type="checkbox" checked={giftWrap} onChange={e=>setGiftWrap(e.target.checked)}/><span>Gói quà inner child <small>Thiệp viết tay + hộp pastel · 80.000₫</small></span></label><button className="add-button" disabled={!available} onClick={()=>variant&&add({slug:product.handle,name:product.title,color:variant.title,giftWrap,price:Number(variant.price.amount)})}>{available?"Thêm vào giỏ":"Tạm hết hàng"}<span>{available?"+":""}</span></button>{images.length>1&&<div className="product-thumbnails">{images.map((image,index)=><button className={index===imageIndex?"active":""} onClick={()=>setImageIndex(index)} key={image.url}><img src={image.url} alt={image.altText||`${product.title} ${index+1}`}/></button>)}</div>}</div></section><section className="shop-promise"><div><span>01</span><h3>In chậm, làm kỹ</h3><p>Mỗi chiếc đèn được in và hoàn thiện bằng tay.</p></div><div><span>02</span><h3>Ảnh thật từ Shopify</h3><p>Ảnh và thông tin được đồng bộ trực tiếp từ sản phẩm bạn đăng.</p></div><div><span>03</span><h3>Cập nhật linh hoạt</h3><p>Thay giá, ảnh và tồn kho mà không cần sửa giao diện.</p></div></section></main>
}
