"use client";
import {use,useEffect,useState} from "react";
import {useCart} from "../cart";
import {money,products} from "../products";
import {track} from "../track";

const reviews=[
 {name:"Vy · Quận 3",rating:"★★★★★",text:"Momo làm góc đầu giường của mình vui hẳn. Ánh sáng ấm, không chói và vân in nhìn ngoài đời rất xinh."},
 {name:"Quân · Thủ Đức",rating:"★★★★★",text:"Mỗi tối bật đèn lên là tín hiệu hết giờ làm. Đóng gói cẩn thận và màu đúng như trên web."},
 {name:"Hà · Đà Nẵng",rating:"★★★★☆",text:"Pip có cá tính nhưng vẫn dễ đặt cạnh đồ gỗ. Mình thích nhất là biết chiếc đèn đã mất bao lâu để in."},
];

export default function ProductPage({params}:{params:Promise<{slug:string}>}){
 const{slug}=use(params);const product=products.find(p=>p.slug===slug);const[color,setColor]=useState(product?.palette[0]??"");const[on,setOn]=useState(true);const[scene,setScene]=useState("bedside");const[giftWrap,setGiftWrap]=useState(false);const[saved,setSaved]=useState(false);const[shareNote,setShareNote]=useState("");const{items,setOpen,add}=useCart();
 useEffect(()=>{if(!product)return;const queryColor=new URLSearchParams(location.search).get("color");if(queryColor&&product.palette.includes(queryColor))setColor(queryColor);const wishlist=JSON.parse(localStorage.getItem("humm-wishlist")||"[]") as string[];setSaved(wishlist.includes(product.slug));track("product_view",product.slug)},[product]);
 if(!product)return <main className="not-found"><h1>Không tìm thấy chiếc đèn này.</h1><a href="/shop">← Về cửa hàng</a></main>;
 const count=items.reduce((s,x)=>s+x.quantity,0);function toggleSaved(){const list=JSON.parse(localStorage.getItem("humm-wishlist")||"[]") as string[];const next=saved?list.filter(x=>x!==product!.slug):[...new Set([...list,product!.slug])];localStorage.setItem("humm-wishlist",JSON.stringify(next));setSaved(!saved);track("wishlist",product!.slug,{saved:!saved})}
 async function share(){const url=`${location.origin}/shop/${product!.slug}?color=${encodeURIComponent(color)}`;const data={title:`${product!.name} · humm.`,text:`Mình vừa phối màu ${color} cho ${product!.name}`,url};try{if(navigator.share)await navigator.share(data);else await navigator.clipboard.writeText(url);setShareNote("Đã copy phối màu ✦");track("share_config",product!.slug,{color})}catch{}}
 return <main className="shop-page"><nav className="nav shop-nav"><a className="logo" href="/">humm<span>.</span></a><div className="top-tabs"><a href="/">Trang chủ</a><a className="active" href="/shop">Cửa hàng</a></div><button className="cart" onClick={()=>setOpen(true)}>Giỏ hàng <b>{count}</b></button></nav>
 <section className={`pdp ${product.color} ${on?"light-on":"light-off"}`}><div className={`pdp-visual room-${scene}`}><a className="back-shop" href="/shop">← Tất cả sản phẩm</a><div className="room-wall"><div className="room-art">inner<br/>child</div><div className="room-table"/><div className="room-books"/></div><div className="ambient-glow"/><div className="lamp pdp-lamp"><div className="lamp-cap"/><div className="lamp-body"><div className="face">•&nbsp;&nbsp;•<br/><small>⌣</small></div></div><div className="lamp-base"/></div><button className="light-switch" onClick={()=>setOn(v=>!v)}><i className={on?"on":""}/>{on?"Lights on":"Lights off"}</button></div>
 <div className="pdp-info"><div className="pdp-actions"><button onClick={toggleSaved}>{saved?"♥ Đã để dành":"♡ Để dành em này"}</button><button onClick={share}>↗ Chia sẻ phối màu</button></div>{shareNote&&<span className="share-note">{shareNote}</span>}<p className="eyebrow">3D printed companion</p><h1>{product.name}</h1><p className="pdp-note">{product.note}</p><strong className="pdp-price">{money(product.price)}</strong><p className="pdp-story">{product.story}</p><fieldset><legend>Chọn màu · <b>{color}</b></legend><div className="swatches">{product.palette.map(c=><button className={`swatch ${c.toLowerCase()} ${color===c?"selected":""}`} onClick={()=>setColor(c)} key={c} aria-label={`Chọn màu ${c}`}/>)}</div></fieldset><label className="gift-option"><input type="checkbox" checked={giftWrap} onChange={e=>setGiftWrap(e.target.checked)}/><span>Gói quà inner child <small>Thiệp viết tay + hộp pastel · 80.000₫</small></span></label><button className="add-button" onClick={()=>add({slug:product.slug,name:product.name,color,giftWrap,price:product.price})}>Thêm vào giỏ <span>+</span></button><div className="specs"><div><span>Kích thước</span><b>{product.size}</b></div><div><span>Thời gian in</span><b>{product.printTime}</b></div><div><span>Ánh sáng</span><b>LED ấm 2700K</b></div><div><span>Bảo hành</span><b>12 tháng</b></div></div></div></section>
 <section className="room-lab"><div><p className="eyebrow">try it in your room</p><h2>Em ấy sẽ sống<br/>ở góc nào?</h2><p>Chọn một bối cảnh để hình dung tỷ lệ thực tế của chiếc đèn.</p></div><div className="scene-options">{[["bedside","Đầu giường"],["desk","Bàn làm việc"],["shelf","Kệ sách"]].map(([id,label])=><button className={scene===id?"active":""} onClick={()=>{setScene(id);track("room_preview",product.slug,{scene:id})}} key={id}><i className={`scene-icon ${id}`}>☼</i><span>{label}</span></button>)}</div></section>
 <section className="making"><div className="making-copy"><p className="eyebrow">made slowly</p><h2>Từ một đường nhựa<br/>thành một người bạn.</h2><p>Nhựa PLA nguồn gốc thực vật được đắp từng lớp mỏng. Sau gần một ngày, humm. kiểm tra bề mặt, lắp ánh sáng và đóng gói bằng tay.</p><div className="process-steps"><span><b>01</b>In 3D<br/><small>18–26 giờ</small></span><span><b>02</b>Hoàn thiện<br/><small>bằng tay</small></span><span><b>03</b>Glow check<br/><small>trước khi gửi</small></span></div></div><div className="print-visual"><div className="print-lines"/><div className="tiny-lamp">h.</div><span>layer by layer</span></div></section>
 <section className="reviews"><div className="reviews-head"><p className="eyebrow">happy homes</p><h2>Người thật,<br/>góc vui thật.</h2><strong>4.8 <span>★★★★★</span></strong></div><div className="review-grid">{reviews.map((r,i)=><article key={r.name}><div className={`review-photo photo-${i+1}`}><span>humm.<br/>at home</span></div><p className="stars">{r.rating}</p><blockquote>“{r.text}”</blockquote><b>{r.name}</b></article>)}</div></section>
 <section className="faq"><div><p className="eyebrow">good to know</p><h2>Trước khi<br/>đón em về.</h2></div><div>{[["Đèn có nóng không?","Không. humm. dùng bóng LED ấm công suất thấp, an toàn khi sử dụng lâu."],["Vệ sinh như thế nào?","Dùng khăn mềm khô hoặc hơi ẩm. Không ngâm nước và không dùng chất tẩy mạnh."],["Đổi trả và bảo hành?","Đổi sản phẩm lỗi trong 7 ngày, bảo hành phần điện 12 tháng."],["Vân in có phải lỗi không?","Không — những đường vân mảnh là dấu vết tự nhiên của quá trình in 3D và làm mỗi chiếc trở nên riêng biệt."]].map(([q,a])=><details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>
 </main>}
