"use client";
import { useEffect, useState } from "react";
import { useCart } from "../cart";
import { money } from "../products";
import { ShopifyProduct, ShopifyVariant } from "../shopify";
import { track } from "../track";

export default function ProductClient({ product }: { product: ShopifyProduct }) {
  const [variant, setVariant] = useState<ShopifyVariant | null>(product.variants.nodes[0] || null), [imageIndex, setImageIndex] = useState(0); const { items, setOpen, add, busy, error } = useCart();
  useEffect(() => { track("product_view", product.handle); }, [product.handle]);
  const count = items.reduce((sum, item) => sum + item.quantity, 0), images = product.images.nodes, currentImage = images[imageIndex], available = !!variant?.availableForSale;
  const optionNames = [...new Set(product.variants.nodes.flatMap(v => v.selectedOptions.map(o => o.name)))].filter(x => x !== "Title");
  const specs = [["Kích thước", product.size?.value], ["Chất liệu", product.material?.value], ["Ánh sáng", product.light?.value], ["Thời gian làm", product.printTime?.value], ["Bảo hành", product.warranty?.value]].filter((x): x is string[] => !!x[1]);
  function chooseOption(name: string, value: string) { const next = product.variants.nodes.find(v => v.selectedOptions.every(o => o.name === name ? o.value === value : variant?.selectedOptions.some(current => current.name === o.name && current.value === o.value))); if (next) setVariant(next); }
  return <main className="shop-page"><nav className="nav shop-nav"><a className="logo" href="/">humm<span>.</span></a><div className="top-tabs"><a href="/">Trang chủ</a><a className="active" href="/shop">Cửa hàng</a></div><button className="cart" onClick={() => setOpen(true)}>Giỏ hàng <b>{count}</b></button></nav><section className="pdp shopify-pdp"><div className={`pdp-visual ${!currentImage ? "empty-product-image" : ""}`}><a className="back-shop" href="/shop">← Tất cả sản phẩm</a>{currentImage ? <img className="pdp-product-image" src={currentImage.url} alt={currentImage.altText || product.title} /> : <span className="media-placeholder">Ảnh sản phẩm đang cập nhật</span>}{images.length > 1 && <button className="light-switch" onClick={() => setImageIndex(i => i === 0 ? 1 : 0)} aria-label="Chuyển giữa ảnh đèn tắt và bật"><i className={imageIndex === 1 ? "on" : ""} />{imageIndex === 0 ? "Đèn tắt" : "Đèn bật"}</button>}</div><div className="pdp-info"><p className="eyebrow">3D printed companion</p><h1>{product.title}</h1>{variant && <strong className="pdp-price">{money(Number(variant.price.amount))}</strong>}{product.description && <p className="pdp-story">{product.description}</p>}{optionNames.map(name => <fieldset key={name}><legend>{name} · <b>{variant?.selectedOptions.find(o => o.name === name)?.value}</b></legend><div className="variant-options">{[...new Set(product.variants.nodes.flatMap(v => v.selectedOptions.filter(o => o.name === name).map(o => o.value)))].map(value => <button type="button" className={variant?.selectedOptions.some(o => o.name === name && o.value === value) ? "selected" : ""} onClick={() => chooseOption(name, value)} key={value}>{value}</button>)}</div></fieldset>)}<button className="add-button sticky-mobile-add" disabled={!available || busy} onClick={() => variant && add(variant.id, product.handle)}>{busy ? "Đang thêm…" : available ? "Thêm vào giỏ" : "Tạm hết hàng"}<span>{available && !busy ? "+" : ""}</span></button>{error && <p className="form-error">{error}</p>}{specs.length > 0 && <dl className="product-specs">{specs.map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>}{images.length > 1 && <div className="product-thumbnails">{images.map((image, index) => <button type="button" aria-label={`Xem ảnh ${index + 1}`} className={index === imageIndex ? "active" : ""} onClick={() => setImageIndex(index)} key={image.url}><img src={image.url} alt={image.altText || `${product.title} ${index + 1}`} /></button>)}</div>}</div></section><section className="shop-promise"><div><span>01</span><h3>In chậm, làm kỹ</h3><p>Mỗi chiếc đèn được in và hoàn thiện bằng tay.</p></div><div><span>02</span><h3>Giá luôn đồng bộ</h3><p>Giỏ hàng đọc trực tiếp giá và tồn kho Shopify.</p></div><div><span>03</span><h3>Thanh toán bảo mật</h3><p>Bạn hoàn tất đơn hàng trên Shopify Checkout.</p></div></section></main>;
}
